### PR TITLE
Completed the addCourse and deleteCourse methods.

### PR DESCRIPTION
**Pull request by mayushanuoft**
addCourse takes a user-inputted string from the searchfield and places it into a list containing all added courses.

deleteCourse takes the most recent addition into the course list and removes it (essentially popping).

In terms of collaboration with the UI, the added courses will be displayed in a label, and deleted courses will be removed from said label.

Next commit will focus on validating the input (ensuring they are legible). Thus, this commit assumes that all inputs are desirable inputs.

### CODE REVIEW

**Review by jfitzgerald1126 — DISMISSED** [review]
Implementation of the addCrouse and deleteCourse methods look good in regards to the scope of JavaFX.

**Review by wahhabaziz — APPROVED** [review]
Methods look well implemented and works well with JavaFX. Looking forward to the next commit to build upon this.

**Review by tuspar — APPROVED** [review]
Required functionality is achieved with these changes. Should eventually be shifted into an `Interactor` object to meet CA standards

**Review by ArsalKhan1 — APPROVED** [review]
addCourse and deleteCourse and implemented well and the functionaility is completed. Collaboration with UI is done effectively and look forward to seeing the next changes.

**Pull request merged**
