### PR TITLE
Search Feature Implementation

### LINKED ISSUE #4: UI
Includes all the features that will be displayed to the user, including the Search feature, displaying timetables, filters, and tags etc.

### PR DESCRIPTION
**Pull request by Maroosh-Gillani**
Contains implementation for the Search Feature (including Autocomplete). The search feature is implemented while utilizing the API class significantly, which means that Unit Tests would be redundant.

### CODE REVIEW

**Review by jfitzgerald1126 — CHANGES_REQUESTED** [review]
Good catch on the new Gradle dependency. However, should the AppController name be called appController per the java naming convention, or is that for methods only?

**Review by jeffzhan — DISMISSED** [review]

**Review by jeffzhan — APPROVED** [review]
Good changes, code is well documented with detailed comments and seems to be following clean code principles

**Review by jfitzgerald1126 — APPROVED** [review]

**Review by mayushanuoft — APPROVED** [review]
Great work! The basics of the search feature were implemented well. Particularly, from line 59-66 (semesterFieldSelected) really adhered to the Open-closed principle, as we can easily extend for the summer semester should we wish to.

**Comment by jfitzgerald1126** [comment]
Consider perhaps adding Junit tests for these code changes. I understand it can be difficult considering the implementation, but it is necessary.

**Pull request merged**
