### PR TITLE
API Bug Fix and Test

### LINKED ISSUE #16: [Bug] API calls to cancelled courses
The API throws JSON exceptions in the following conditions:

- Meeting is Cancelled
- The Course does not exist and a blank JSONArray is returned 
- The meeting has an invalid start/end time

The behavior can be reproduced by:

```
API api = new API();
api.getCourse("CSC258H1-S-20229", false)
```

This issue is common when calling courses during the Spring semester or querying for STA courses.

### PR DESCRIPTION
**Pull request by tuspar**
This fix keeps the interface of the API the same to ensure minimal changes to any dependencies. The test introduced is very computationally heavy however ensures that the API works for a vast array of courses.  This pull request closes #16.

### CODE REVIEW

**Review by Maroosh-Gillani — APPROVED** [review]
Code fixed bugs and added a test to ensure that it was fixed. This fix should also help with the implementation of the search feature. Other than that, code is well documented and commented. Seems to follow clean architecture and SOLID principles as well. Commit message also explains the fix well.

**Review by jeffzhan — APPROVED** [review]
Fixes bugs and typos and cleans up a few small things. More importantly, fixes search implementation which will be useful. Test is comprehensive and covers many cases. 

Code is documented well with comments and adheres well to clean architecture and design.

**Review by wahhabaziz — APPROVED** [review]
Test and fixes seem to be implemented correctly - no further work needed.

**Comment by tuspar** [comment]
This issue was caused by parsing data on cancelled sections. It was difficult to identify due to the less informative errors thrown by the `org.json` package used for JSON processing and was instead identified by stepping through the each API call. To remedy this, in the future the `.get().toString()` function must be instead of the `getString()` function for nullable properties. This bug was introduced into the code due to a lack of documentation of the UofT Arts & Science Timetable API. The Java API was made by the reviewing courses during the Fall session which were less likely to be cancelled whereas Winter courses were more likely. This problem is now tested for by parsing all courses in the Timetable. Another bug that was discovered was in the UofT API where the `org` parameter did not work for STA courses. This has been fixed by changing the `org` parameter to `code` which gives the same result but accounts for `STA` courses.

**Pull request merged**
