### PR TITLE
Changed the sort method for RMP to fit proper arguments needed

### LINKED ISSUE #55: Rate my prof syntax change
**Describe the bug**

**To Reproduce**
1. Go to 'RateMyProfInteractor'
2. Click on 'RateMyProfInteractor'
3. Scroll down to 'function call for TSort.sort'

**Expected behavior**
Doesn't need the timetable list argument.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by jfitzgerald1126**
---
name: 55-rate-my-prof-syntax-change
about: Syntax changes
title: 'fixes'
labels: 'bug'
assignees: 'jfitzgerald1126'

---

**Describe your changes**

Syntax fix

**Checklist before requesting a review**
- [x] I have performed a self-review of my code
- [ ] I have added thorough tests
- [x] A pull request for this issue does not already exist
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, and added JavaDocs

### CODE REVIEW

**Comment by jfitzgerald1126** [comment]
Failing test because waiting for code to be pushed onto main

**Review by wahhabaziz — APPROVED** [review]
This change keeps up to date with my new PR as well - good job on communicating that these bugs are now addressed.

**Review by Maroosh-Gillani — APPROVED** [review]
Nice work, needed changes.

**Review by tuspar — APPROVED** [review]
Good changes to fit naming scheme.

**Pull request merged**
