### PR TITLE
Extracted methods and changed HashMap -> Map and HashSet -> Set

### PR DESCRIPTION
**Pull request by jfitzgerald1126**

### CODE REVIEW

**Review by wahhabaziz — DISMISSED** [review]
Changes are simple and now avoids code smells, no further work needed.

**Review by Maroosh-Gillani — DISMISSED** [review]
Mainly just changes the type of object from HashMap and HashSet to Map and Set, which is done so correctly. Also adds proper JavaDoc and comments for any methods that have been added. There seem to be conflicts with the main file however so make sure to fix those before merging. Good job otherwise!

**Review by tuspar — APPROVED** [review]
The use of an interface over the implementation is good for maintainability and SOLID principles. Variables names are also much clearer

**Review by Maroosh-Gillani — APPROVED** [review]
Merged Conflicts have been fixed, and my previous review still applies. Awesome work!

**Review by ZeeGazi — APPROVED** [review]
Smart choice of using map and set instead of HashMap and HashSet since the first two are interfaces, whereas the second two are specific implementations. Also changing the variable names made them more informative.

**Pull request merged**
