### PR TITLE
Implemented Timetable Persistence

### LINKED ISSUE #5: Timetable Persistence
Saves to local files or to iCalendar format

### PR DESCRIPTION
**Pull request by ArsalKhan1**
Implemented the Timetable Persistence by converting the Timetable Arraylist to a JSON Object. Then, I wrote the JSON Object to a .JSON file. This will allow me to read the JSON file and convert it back into a Timetable Arraylist when called.

### CODE REVIEW

**Review by jfitzgerald1126 — CHANGES_REQUESTED** [review]
Good progress towards creating persistence. However, I think the class name would make more sense as saveToJSON. Furthermore, we should have Javadoc for both the class and the methods. Good work with the error-catching. I think we should follow the workflow and create Junit testing before writing concrete code implementation. Looking forward to the code improvements.

**Review by ZeeGazi — DISMISSED** [review]
Good choice of changing the Timetable Arraylist to a JSON Object. This is helpful because the Timetable Arraylist can be read in the JSON file as a JSON object, and when it is needed it can be changed back into a Timetable Arraylist.

**Review by jeffzhan — CHANGES_REQUESTED** [review]
I agree with @jfitzgerald1126 in that Junit testing should be added, it is more proper that way. Some documentation or comments would also be appreciated to more easily understand the code. Otherwise, the code looks polished and I look forward to its completion.

**Comment by ArsalKhan1** [comment]
Implemented TimetableReaderWriter using Jackson writing the Timetable ArrayList to a JSON object and saving it as a .json file. Then, java reads the JSON file and converts it to an ArrayList. Also, implemented Testing in TimetableReaderWriterTest.java to test the functionality implemented. I have also written Javadocs for both the classes and methods as advised by @jfitzgerald1126 and @jeffzhan.

**Review by jfitzgerald1126 — DISMISSED** [review]
Good job adding Junit tests as per request and implementing the reading feature along with your original submission of the JSON writer. We should still consider changing Json to JSON as per the correct naming convention. Good work!

**Review by jeffzhan — APPROVED** [review]
Great implementation, the Javadocs and tests are well done and a good addition.

**Comment by tuspar** [comment]
The branch these changes are on is 24 commits behind main and thus has many merge conflicts that are difficult to resolve. As a result changes on this branch have now been implemented on #31.

**Pull request closed without merging**
