### PR TITLE
Added tests for persistence

### LINKED ISSUE #48: Persistence Tests
**Describe the bug**
Tests are needed for the persistence use case.

**To Reproduce**
1. Go to use_cases
2. Click on persistence

**Expected behavior**
Testing class file required for persistence.

### PR DESCRIPTION
**Pull request by ArsalKhan1**
---
name: Persistence Test
about: Tests

---

**Describe your changes**

Tests were added to check persistence

**Checklist before requesting a review**
- [x] I have performed a self-review of my code
- [X] I have added thorough tests
- [X] A pull request for this issue does not already exist
- [X] My code follows the style guidelines of this project
- [X] I have commented my code, and added JavaDocs

### CODE REVIEW

**Review by jeffzhan — APPROVED** [review]
Good addition of tests that are appropriate and have wide coverage

**Review by tuspar — APPROVED** [review]
Excellent test coverage and documentation.

**Review by Maroosh-Gillani — COMMENTED** [review]
great coverage and tests, good use of template

**Review by Maroosh-Gillani — APPROVED** [review]
great coverage and tests, good use of template

**Pull request merged**
