### PR TITLE
API

### LINKED ISSUE #1: API
Gets data from the UofT ArtsSci API and converts it to Dataclasses that are easier to work with

### PR DESCRIPTION
**Pull request by tuspar**

### CODE REVIEW

**Review by ZeeGazi — APPROVED** [review]
Classes have been revised and additional methods have been correctly implemented, as well as testing to ensure the validity of these classes.

**Review by Maroosh-Gillani — APPROVED** [review]
All functions/attributes etc. are commented. Can't see any code smells as far as I can tell. Issue with the last test seems to have been resolved. Unit tests have been provided for the main functions. Naming conventions used are straightforward so it makes code easy to understand (commenting as mentioned above helps with that too). So far so good

**Comment by jfitzgerald1126** [comment]
Good job adding unit tests. Maybe our commit messages could be clearer but we can work on that in the future.

**Review by jfitzgerald1126 — APPROVED** [review]
Good work writing the unit tests. I think our commit messages can be more clear/descriptive in the future.

**Comment by tuspar** [comment]
This pull request introduces the gateway to the UofT Arts & Science Timetable API and it's corresponding use-case, the CourseBuilder that communicates with the Course, Meeting and Session entities, all following Clean Architecture principles as well as applying the Builder data pattern required due to the flexibility required when creating Course entities. The tests introduced also have 100% percent code coverage. A good future improvement to the tests would be to introduce tests that account for exception that may be thrown by the API.

**Pull request merged**
