### PR TITLE
2 dataclasses

### PR DESCRIPTION
**Pull request by jfitzgerald1126**

### CODE REVIEW

**Review by Maroosh-Gillani — DISMISSED** [review]
Looks good, everything makes sense so far. Just not sure that if everyone approves these changes, will the entire issue close? Because I don't think we want this issue to close at this stage, right?

**Review by tuspar — APPROVED** [review]
All classes are well documented and completes our entity layer and forms a good framework for everyone to start working.

**Review by wahhabaziz — APPROVED** [review]
Classes follow clean architecture and creates a foundation for later implementations.

**Review by ArsalKhan1 — APPROVED** [review]
Dataclasses are completed using class requirements and follow the CRC guidelines.

**Review by ZeeGazi — APPROVED** [review]
Good start to the classes, the next steps of implementation can be commenced.

**Pull request merged**
