### PR TITLE
refactoring small changes

### LINKED ISSUE #41: Refactoring
need refactoring for code smells

### PR DESCRIPTION
**Pull request by jeffzhan**
---
name: refactoring
about: refactored bunch of stuff based on suggestions from sonarlint
title: refactoring
labels: refactoring
assignees: jeffzhan

---

 refactored bunch of stuff based on suggestions from sonarlint

**Checklist before requesting a review**
- [X] I have performed a self-review of my code
- [X] I have added thorough tests
- [X] A pull request for this issue does not already exist
- [X] My code follows the style guidelines of this project
- [X] I have commented my code, and added JavaDocs

### CODE REVIEW

**Review by tuspar — DISMISSED** [review]
Good changes to fix warnings and code smells

**Review by jfitzgerald1126 — DISMISSED** [review]
Refactoring changes appear to better follow CA and fix code smells.

**Review by tuspar — APPROVED** [review]
Good changes to fix warnings and code smells

**Review by ArsalKhan1 — APPROVED** [review]
Refactoring edits are done correctly and helpful. The code seems cleaner and more readable now.

**Review by jfitzgerald1126 — APPROVED** [review]

**Pull request merged**
