### PR TITLE
Timetable Generation

### LINKED ISSUE #3: Timetable Generation
Generate all the possible timetables and remove the invalid class and tag the remaining classes

### PR DESCRIPTION
**Pull request by ZeeGazi**
This code implements testing for Timetable Generation, specifically for TimetableValidator. It checks various cases to dictate whether two meetings overlap. One case checks whether two meetings which are on two separate days are valid. Another case checks if two meetings are valid if they are on the same day. TimetableFactory is also implemented which generates all possible combinations of timetables but omits certain combinations in the case tutorials or practicals occur at the same time; since that would reduce the large number of Timetables that are possible to generate.

### CODE REVIEW

**Review by jeffzhan — APPROVED** [review]
Great changes, the code is written well and clean with detailed documentation as well as comments for most things. Tests are efficient and seem to have proper and wide coverage as well, even descriptions for certain ones.

**Review by wahhabaziz — APPROVED** [review]
Changes are well made - tests everything which the timetable generation does and is well formatted. Can always be updated future for any further implementations.

**Review by Maroosh-Gillani — APPROVED** [review]
Efficient implementation of JavaDocs which makes the code easier to understand, are also very detailed. Tests are also included with good coverage. Also good changes in terms of naming conventions and attribute/variable type changes.

**Review by jfitzgerald1126 — APPROVED** [review]
Good job creating a comprehensive set of test cases providing near-full code coverage. This should be ready to be merged with the main branch.

**Pull request merged**
