### PR TITLE
Altered the implementation of the Search Feature slightly to better f…

### PR DESCRIPTION
**Pull request by Maroosh-Gillani**
…it with Clean Architecture and SOLID principles by introducing additional classes such as AutoCompleteInteractor, AutoCompleteRequestModel,AutoCompleteResponseModel and ErrorWindow. Also introduced an interface: AutoCompleteInputBoundary. Each class basically has components of what the search feature implementation was initially in AppController but makes it follow the CA and SOLID requirements better. JavaDocs and Comments to be added.

### CODE REVIEW

**Comment by Maroosh-Gillani** [comment]
Forgot to remove a chunk of commented out code, will fix alongside JavaDocs/Comment additions.

**Review by tuspar — APPROVED** [review]
Introduction of a `use_case.auto_complete` package follows the code organization guideline. The interactor, input boundary, request model and response model serve as layer between Controller and Gateway. The introduction of `ErrorWindow` as a presenter also delegates the responsibility of showing errors to a seperate class. Altogether these changes massively improve our adherence to CA. Tests must be introduced for the added files whenever possible.

**Review by wahhabaziz — APPROVED** [review]
New implementations adheres to clean architecture. Tests being added as soon as possible is the next step, good stuff!

**Review by jfitzgerald1126 — APPROVED** [review]
Good work inverting the dependencies on upper layers by introducing interfaces for the input boundary. We should continue to fix these dependencies for other facets of our project.

**Pull request merged**
