### PR TITLE
Missing Documentation

### LINKED ISSUE #53: Missing Documentation
**Describe the bug**
Missing Documentation

### PR DESCRIPTION
**Pull request by tuspar**
**Missing Documentation**

- [X] TimetableViewer
- [X] AppController
- [X] ErrorWindow

Closes #53.

### CODE REVIEW

**Review by wahhabaziz — DISMISSED** [review]
These documents are now well documented and provide a great snippet of information for what they do - good stuff.

**Review by wahhabaziz — APPROVED** [review]
More documentation added, my comment from before still holds.

**Review by jeffzhan — APPROVED** [review]
I love documentation great job

**Review by jfitzgerald1126 — APPROVED** [review]
Documentation accurately describes the code.

**Pull request merged**
